// Auto-generated. Do not edit!

// (in-package wasp_logistics.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class LogisticsResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.liftup_ = null;
      this.liftdown_ = null;
      this.final = null;
    }
    else {
      if (initObj.hasOwnProperty('liftup_')) {
        this.liftup_ = initObj.liftup_
      }
      else {
        this.liftup_ = 0;
      }
      if (initObj.hasOwnProperty('liftdown_')) {
        this.liftdown_ = initObj.liftdown_
      }
      else {
        this.liftdown_ = 0;
      }
      if (initObj.hasOwnProperty('final')) {
        this.final = initObj.final
      }
      else {
        this.final = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type LogisticsResult
    // Serialize message field [liftup_]
    bufferOffset = _serializer.int32(obj.liftup_, buffer, bufferOffset);
    // Serialize message field [liftdown_]
    bufferOffset = _serializer.int32(obj.liftdown_, buffer, bufferOffset);
    // Serialize message field [final]
    bufferOffset = _serializer.int32(obj.final, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type LogisticsResult
    let len;
    let data = new LogisticsResult(null);
    // Deserialize message field [liftup_]
    data.liftup_ = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [liftdown_]
    data.liftdown_ = _deserializer.int32(buffer, bufferOffset);
    // Deserialize message field [final]
    data.final = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'wasp_logistics/LogisticsResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '609a04ed842c289f52a4ee3c9b0c5e0f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    int32 liftup_
    int32 liftdown_
    int32 final
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new LogisticsResult(null);
    if (msg.liftup_ !== undefined) {
      resolved.liftup_ = msg.liftup_;
    }
    else {
      resolved.liftup_ = 0
    }

    if (msg.liftdown_ !== undefined) {
      resolved.liftdown_ = msg.liftdown_;
    }
    else {
      resolved.liftdown_ = 0
    }

    if (msg.final !== undefined) {
      resolved.final = msg.final;
    }
    else {
      resolved.final = 0
    }

    return resolved;
    }
};

module.exports = LogisticsResult;
