// Auto-generated. Do not edit!

// (in-package wasp_logistics.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class TrolleyAlignGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.align = null;
    }
    else {
      if (initObj.hasOwnProperty('align')) {
        this.align = initObj.align
      }
      else {
        this.align = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TrolleyAlignGoal
    // Serialize message field [align]
    bufferOffset = _serializer.bool(obj.align, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type TrolleyAlignGoal
    let len;
    let data = new TrolleyAlignGoal(null);
    // Deserialize message field [align]
    data.align = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'wasp_logistics/TrolleyAlignGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '3d78b99c0a1f9f75d262b241769b0800';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal definition
    bool align
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TrolleyAlignGoal(null);
    if (msg.align !== undefined) {
      resolved.align = msg.align;
    }
    else {
      resolved.align = false
    }

    return resolved;
    }
};

module.exports = TrolleyAlignGoal;
