// Generated by gencpp from file wasp_joy/GetPose.msg
// DO NOT EDIT!


#ifndef WASP_JOY_MESSAGE_GETPOSE_H
#define WASP_JOY_MESSAGE_GETPOSE_H

#include <ros/service_traits.h>


#include <wasp_joy/GetPoseRequest.h>
#include <wasp_joy/GetPoseResponse.h>


namespace wasp_joy
{

struct GetPose
{

typedef GetPoseRequest Request;
typedef GetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPose
} // namespace wasp_joy


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wasp_joy::GetPose > {
  static const char* value()
  {
    return "d5621c4e029c396eafa0fc5c878af17c";
  }

  static const char* value(const ::wasp_joy::GetPose&) { return value(); }
};

template<>
struct DataType< ::wasp_joy::GetPose > {
  static const char* value()
  {
    return "wasp_joy/GetPose";
  }

  static const char* value(const ::wasp_joy::GetPose&) { return value(); }
};


// service_traits::MD5Sum< ::wasp_joy::GetPoseRequest> should match
// service_traits::MD5Sum< ::wasp_joy::GetPose >
template<>
struct MD5Sum< ::wasp_joy::GetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wasp_joy::GetPose >::value();
  }
  static const char* value(const ::wasp_joy::GetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wasp_joy::GetPoseRequest> should match
// service_traits::DataType< ::wasp_joy::GetPose >
template<>
struct DataType< ::wasp_joy::GetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::wasp_joy::GetPose >::value();
  }
  static const char* value(const ::wasp_joy::GetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wasp_joy::GetPoseResponse> should match
// service_traits::MD5Sum< ::wasp_joy::GetPose >
template<>
struct MD5Sum< ::wasp_joy::GetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wasp_joy::GetPose >::value();
  }
  static const char* value(const ::wasp_joy::GetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wasp_joy::GetPoseResponse> should match
// service_traits::DataType< ::wasp_joy::GetPose >
template<>
struct DataType< ::wasp_joy::GetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::wasp_joy::GetPose >::value();
  }
  static const char* value(const ::wasp_joy::GetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WASP_JOY_MESSAGE_GETPOSE_H
