// Generated by gencpp from file wasp_joy/GetPoseResponse.msg
// DO NOT EDIT!


#ifndef WASP_JOY_MESSAGE_GETPOSERESPONSE_H
#define WASP_JOY_MESSAGE_GETPOSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wasp_joy
{
template <class ContainerAllocator>
struct GetPoseResponse_
{
  typedef GetPoseResponse_<ContainerAllocator> Type;

  GetPoseResponse_()
    : x(0.0)
    , y(0.0)
    , theta_z(0.0)
    , theta_w(0.0)  {
    }
  GetPoseResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta_z(0.0)
    , theta_w(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _theta_z_type;
  _theta_z_type theta_z;

   typedef double _theta_w_type;
  _theta_w_type theta_w;





  typedef boost::shared_ptr< ::wasp_joy::GetPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wasp_joy::GetPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPoseResponse_

typedef ::wasp_joy::GetPoseResponse_<std::allocator<void> > GetPoseResponse;

typedef boost::shared_ptr< ::wasp_joy::GetPoseResponse > GetPoseResponsePtr;
typedef boost::shared_ptr< ::wasp_joy::GetPoseResponse const> GetPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wasp_joy::GetPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wasp_joy::GetPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wasp_joy::GetPoseResponse_<ContainerAllocator1> & lhs, const ::wasp_joy::GetPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta_z == rhs.theta_z &&
    lhs.theta_w == rhs.theta_w;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wasp_joy::GetPoseResponse_<ContainerAllocator1> & lhs, const ::wasp_joy::GetPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wasp_joy

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wasp_joy::GetPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wasp_joy::GetPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wasp_joy::GetPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wasp_joy::GetPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wasp_joy::GetPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wasp_joy::GetPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wasp_joy::GetPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1505004303e1bde4065ebaa176f79fb9";
  }

  static const char* value(const ::wasp_joy::GetPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1505004303e1bde4ULL;
  static const uint64_t static_value2 = 0x065ebaa176f79fb9ULL;
};

template<class ContainerAllocator>
struct DataType< ::wasp_joy::GetPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wasp_joy/GetPoseResponse";
  }

  static const char* value(const ::wasp_joy::GetPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wasp_joy::GetPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float64 x\n"
"float64 y\n"
"float64 theta_z\n"
"float64 theta_w\n"
"\n"
;
  }

  static const char* value(const ::wasp_joy::GetPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wasp_joy::GetPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta_z);
      stream.next(m.theta_w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wasp_joy::GetPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wasp_joy::GetPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta_z: ";
    Printer<double>::stream(s, indent + "  ", v.theta_z);
    s << indent << "theta_w: ";
    Printer<double>::stream(s, indent + "  ", v.theta_w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WASP_JOY_MESSAGE_GETPOSERESPONSE_H
