; Auto-generated. Do not edit!


(cl:in-package wasp_logistics-msg)


;//! \htmlinclude LogisticsActionGoal.msg.html

(cl:defclass <LogisticsActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type wasp_logistics-msg:LogisticsGoal
    :initform (cl:make-instance 'wasp_logistics-msg:LogisticsGoal)))
)

(cl:defclass LogisticsActionGoal (<LogisticsActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LogisticsActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LogisticsActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name wasp_logistics-msg:<LogisticsActionGoal> is deprecated: use wasp_logistics-msg:LogisticsActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <LogisticsActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader wasp_logistics-msg:header-val is deprecated.  Use wasp_logistics-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <LogisticsActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader wasp_logistics-msg:goal_id-val is deprecated.  Use wasp_logistics-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <LogisticsActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader wasp_logistics-msg:goal-val is deprecated.  Use wasp_logistics-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LogisticsActionGoal>) ostream)
  "Serializes a message object of type '<LogisticsActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LogisticsActionGoal>) istream)
  "Deserializes a message object of type '<LogisticsActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LogisticsActionGoal>)))
  "Returns string type for a message object of type '<LogisticsActionGoal>"
  "wasp_logistics/LogisticsActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LogisticsActionGoal)))
  "Returns string type for a message object of type 'LogisticsActionGoal"
  "wasp_logistics/LogisticsActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LogisticsActionGoal>)))
  "Returns md5sum for a message object of type '<LogisticsActionGoal>"
  "23dd76de537ba1274182942ef637dc62")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LogisticsActionGoal)))
  "Returns md5sum for a message object of type 'LogisticsActionGoal"
  "23dd76de537ba1274182942ef637dc62")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LogisticsActionGoal>)))
  "Returns full string definition for message of type '<LogisticsActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%LogisticsGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: wasp_logistics/LogisticsGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%bool active~%float32 distance~%int32 liftup~%int32 liftdown~%#float32 startpoint_x~%#float32 startpoint_y~%#float32 startpoint_z~%#float32 startpoint_w~%#float32 endpoint_x~%#float32 endpoint_y~%#float32 endpoint_z~%#float32 endpoint_w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LogisticsActionGoal)))
  "Returns full string definition for message of type 'LogisticsActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%LogisticsGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: wasp_logistics/LogisticsGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%bool active~%float32 distance~%int32 liftup~%int32 liftdown~%#float32 startpoint_x~%#float32 startpoint_y~%#float32 startpoint_z~%#float32 startpoint_w~%#float32 endpoint_x~%#float32 endpoint_y~%#float32 endpoint_z~%#float32 endpoint_w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LogisticsActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LogisticsActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'LogisticsActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
