; Auto-generated. Do not edit!


(cl:in-package wasp_logistics-msg)


;//! \htmlinclude TrolleyAlignResult.msg.html

(cl:defclass <TrolleyAlignResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass TrolleyAlignResult (<TrolleyAlignResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TrolleyAlignResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TrolleyAlignResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name wasp_logistics-msg:<TrolleyAlignResult> is deprecated: use wasp_logistics-msg:TrolleyAlignResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <TrolleyAlignResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader wasp_logistics-msg:success-val is deprecated.  Use wasp_logistics-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TrolleyAlignResult>) ostream)
  "Serializes a message object of type '<TrolleyAlignResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TrolleyAlignResult>) istream)
  "Deserializes a message object of type '<TrolleyAlignResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TrolleyAlignResult>)))
  "Returns string type for a message object of type '<TrolleyAlignResult>"
  "wasp_logistics/TrolleyAlignResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TrolleyAlignResult)))
  "Returns string type for a message object of type 'TrolleyAlignResult"
  "wasp_logistics/TrolleyAlignResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TrolleyAlignResult>)))
  "Returns md5sum for a message object of type '<TrolleyAlignResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TrolleyAlignResult)))
  "Returns md5sum for a message object of type 'TrolleyAlignResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TrolleyAlignResult>)))
  "Returns full string definition for message of type '<TrolleyAlignResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TrolleyAlignResult)))
  "Returns full string definition for message of type 'TrolleyAlignResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TrolleyAlignResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TrolleyAlignResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TrolleyAlignResult
    (cl:cons ':success (success msg))
))
