; Auto-generated. Do not edit!


(cl:in-package wasp_logistics-msg)


;//! \htmlinclude TrolleyAlignFeedback.msg.html

(cl:defclass <TrolleyAlignFeedback> (roslisp-msg-protocol:ros-message)
  ((align_distance
    :reader align_distance
    :initarg :align_distance
    :type cl:float
    :initform 0.0))
)

(cl:defclass TrolleyAlignFeedback (<TrolleyAlignFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TrolleyAlignFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TrolleyAlignFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name wasp_logistics-msg:<TrolleyAlignFeedback> is deprecated: use wasp_logistics-msg:TrolleyAlignFeedback instead.")))

(cl:ensure-generic-function 'align_distance-val :lambda-list '(m))
(cl:defmethod align_distance-val ((m <TrolleyAlignFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader wasp_logistics-msg:align_distance-val is deprecated.  Use wasp_logistics-msg:align_distance instead.")
  (align_distance m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TrolleyAlignFeedback>) ostream)
  "Serializes a message object of type '<TrolleyAlignFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'align_distance))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TrolleyAlignFeedback>) istream)
  "Deserializes a message object of type '<TrolleyAlignFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'align_distance) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TrolleyAlignFeedback>)))
  "Returns string type for a message object of type '<TrolleyAlignFeedback>"
  "wasp_logistics/TrolleyAlignFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TrolleyAlignFeedback)))
  "Returns string type for a message object of type 'TrolleyAlignFeedback"
  "wasp_logistics/TrolleyAlignFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TrolleyAlignFeedback>)))
  "Returns md5sum for a message object of type '<TrolleyAlignFeedback>"
  "b7244dbdfcdb44c8b9d2912950696c78")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TrolleyAlignFeedback)))
  "Returns md5sum for a message object of type 'TrolleyAlignFeedback"
  "b7244dbdfcdb44c8b9d2912950696c78")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TrolleyAlignFeedback>)))
  "Returns full string definition for message of type '<TrolleyAlignFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 align_distance~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TrolleyAlignFeedback)))
  "Returns full string definition for message of type 'TrolleyAlignFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 align_distance~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TrolleyAlignFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TrolleyAlignFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TrolleyAlignFeedback
    (cl:cons ':align_distance (align_distance msg))
))
