(cl:defpackage wasp_logistics-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "BADTWOINTS"
   "<BADTWOINTS-REQUEST>"
   "BADTWOINTS-REQUEST"
   "<BADTWOINTS-RESPONSE>"
   "BADTWOINTS-RESPONSE"
   "GETPOSE"
   "<GETPOSE-REQUEST>"
   "GETPOSE-REQUEST"
   "<GETPOSE-RESPONSE>"
   "GETPOSE-RESPONSE"
  ))

