(cl:defpackage waypoint_navi-msg
  (:use )
  (:export
   "<WPEXECUTEACTION>"
   "WPEXECUTEACTION"
   "<WPEXECUTEACTIONFEEDBACK>"
   "WPEXECUTEACTIONFEEDBACK"
   "<WPEXECUTEACTIONGOAL>"
   "WPEXECUTEACTIONGOAL"
   "<WPEXECUTEACTIONRESULT>"
   "WPEXECUTEACTIONRESULT"
   "<WPEXECUTEFEEDBACK>"
   "WPEXECUTEFEEDBACK"
   "<WPEXECUTEGOAL>"
   "WPEXECUTEGOAL"
   "<WPEXECUTERESULT>"
   "WPEXECUTERESULT"
  ))

