; Auto-generated. Do not edit!


(cl:in-package waypoint_navi-msg)


;//! \htmlinclude wpexecuteGoal.msg.html

(cl:defclass <wpexecuteGoal> (roslisp-msg-protocol:ros-message)
  ((execute
    :reader execute
    :initarg :execute
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass wpexecuteGoal (<wpexecuteGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <wpexecuteGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'wpexecuteGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name waypoint_navi-msg:<wpexecuteGoal> is deprecated: use waypoint_navi-msg:wpexecuteGoal instead.")))

(cl:ensure-generic-function 'execute-val :lambda-list '(m))
(cl:defmethod execute-val ((m <wpexecuteGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader waypoint_navi-msg:execute-val is deprecated.  Use waypoint_navi-msg:execute instead.")
  (execute m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <wpexecuteGoal>) ostream)
  "Serializes a message object of type '<wpexecuteGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'execute) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <wpexecuteGoal>) istream)
  "Deserializes a message object of type '<wpexecuteGoal>"
    (cl:setf (cl:slot-value msg 'execute) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<wpexecuteGoal>)))
  "Returns string type for a message object of type '<wpexecuteGoal>"
  "waypoint_navi/wpexecuteGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'wpexecuteGoal)))
  "Returns string type for a message object of type 'wpexecuteGoal"
  "waypoint_navi/wpexecuteGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<wpexecuteGoal>)))
  "Returns md5sum for a message object of type '<wpexecuteGoal>"
  "371e747b927788fd0b8812d474ff9a56")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'wpexecuteGoal)))
  "Returns md5sum for a message object of type 'wpexecuteGoal"
  "371e747b927788fd0b8812d474ff9a56")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<wpexecuteGoal>)))
  "Returns full string definition for message of type '<wpexecuteGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%bool execute~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'wpexecuteGoal)))
  "Returns full string definition for message of type 'wpexecuteGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%bool execute~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <wpexecuteGoal>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <wpexecuteGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'wpexecuteGoal
    (cl:cons ':execute (execute msg))
))
