# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from wasp_joy/logistics.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class logistics(genpy.Message):
  _md5sum = "cab0a4435034735f1a142bf0d06c3d35"
  _type = "wasp_joy/logistics"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 liftup
float64 liftdown
float64 lifthome
float64 extrude
float64 intrude
"""
  __slots__ = ['liftup','liftdown','lifthome','extrude','intrude']
  _slot_types = ['float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       liftup,liftdown,lifthome,extrude,intrude

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(logistics, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.liftup is None:
        self.liftup = 0.
      if self.liftdown is None:
        self.liftdown = 0.
      if self.lifthome is None:
        self.lifthome = 0.
      if self.extrude is None:
        self.extrude = 0.
      if self.intrude is None:
        self.intrude = 0.
    else:
      self.liftup = 0.
      self.liftdown = 0.
      self.lifthome = 0.
      self.extrude = 0.
      self.intrude = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5d().pack(_x.liftup, _x.liftdown, _x.lifthome, _x.extrude, _x.intrude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.liftup, _x.liftdown, _x.lifthome, _x.extrude, _x.intrude,) = _get_struct_5d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5d().pack(_x.liftup, _x.liftdown, _x.lifthome, _x.extrude, _x.intrude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.liftup, _x.liftdown, _x.lifthome, _x.extrude, _x.intrude,) = _get_struct_5d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5d = None
def _get_struct_5d():
    global _struct_5d
    if _struct_5d is None:
        _struct_5d = struct.Struct("<5d")
    return _struct_5d
