// Generated by gencpp from file wasp_logistics/GetPoseResponse.msg
// DO NOT EDIT!


#ifndef WASP_LOGISTICS_MESSAGE_GETPOSERESPONSE_H
#define WASP_LOGISTICS_MESSAGE_GETPOSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wasp_logistics
{
template <class ContainerAllocator>
struct GetPoseResponse_
{
  typedef GetPoseResponse_<ContainerAllocator> Type;

  GetPoseResponse_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
    }
  GetPoseResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::wasp_logistics::GetPoseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wasp_logistics::GetPoseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPoseResponse_

typedef ::wasp_logistics::GetPoseResponse_<std::allocator<void> > GetPoseResponse;

typedef boost::shared_ptr< ::wasp_logistics::GetPoseResponse > GetPoseResponsePtr;
typedef boost::shared_ptr< ::wasp_logistics::GetPoseResponse const> GetPoseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wasp_logistics::GetPoseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wasp_logistics::GetPoseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wasp_logistics::GetPoseResponse_<ContainerAllocator1> & lhs, const ::wasp_logistics::GetPoseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wasp_logistics::GetPoseResponse_<ContainerAllocator1> & lhs, const ::wasp_logistics::GetPoseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wasp_logistics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wasp_logistics::GetPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wasp_logistics::GetPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wasp_logistics::GetPoseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wasp_logistics::GetPoseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wasp_logistics::GetPoseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wasp_logistics::GetPoseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wasp_logistics::GetPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "938fa65709584ad8e77d238529be13b8";
  }

  static const char* value(const ::wasp_logistics::GetPoseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x938fa65709584ad8ULL;
  static const uint64_t static_value2 = 0xe77d238529be13b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::wasp_logistics::GetPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wasp_logistics/GetPoseResponse";
  }

  static const char* value(const ::wasp_logistics::GetPoseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wasp_logistics::GetPoseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
;
  }

  static const char* value(const ::wasp_logistics::GetPoseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wasp_logistics::GetPoseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPoseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wasp_logistics::GetPoseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wasp_logistics::GetPoseResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WASP_LOGISTICS_MESSAGE_GETPOSERESPONSE_H
