// Generated by gencpp from file wasp_logistics/GetPose.msg
// DO NOT EDIT!


#ifndef WASP_LOGISTICS_MESSAGE_GETPOSE_H
#define WASP_LOGISTICS_MESSAGE_GETPOSE_H

#include <ros/service_traits.h>


#include <wasp_logistics/GetPoseRequest.h>
#include <wasp_logistics/GetPoseResponse.h>


namespace wasp_logistics
{

struct GetPose
{

typedef GetPoseRequest Request;
typedef GetPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPose
} // namespace wasp_logistics


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wasp_logistics::GetPose > {
  static const char* value()
  {
    return "5cf41b477a9443795d118795e7f68e1a";
  }

  static const char* value(const ::wasp_logistics::GetPose&) { return value(); }
};

template<>
struct DataType< ::wasp_logistics::GetPose > {
  static const char* value()
  {
    return "wasp_logistics/GetPose";
  }

  static const char* value(const ::wasp_logistics::GetPose&) { return value(); }
};


// service_traits::MD5Sum< ::wasp_logistics::GetPoseRequest> should match
// service_traits::MD5Sum< ::wasp_logistics::GetPose >
template<>
struct MD5Sum< ::wasp_logistics::GetPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wasp_logistics::GetPose >::value();
  }
  static const char* value(const ::wasp_logistics::GetPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wasp_logistics::GetPoseRequest> should match
// service_traits::DataType< ::wasp_logistics::GetPose >
template<>
struct DataType< ::wasp_logistics::GetPoseRequest>
{
  static const char* value()
  {
    return DataType< ::wasp_logistics::GetPose >::value();
  }
  static const char* value(const ::wasp_logistics::GetPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wasp_logistics::GetPoseResponse> should match
// service_traits::MD5Sum< ::wasp_logistics::GetPose >
template<>
struct MD5Sum< ::wasp_logistics::GetPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wasp_logistics::GetPose >::value();
  }
  static const char* value(const ::wasp_logistics::GetPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wasp_logistics::GetPoseResponse> should match
// service_traits::DataType< ::wasp_logistics::GetPose >
template<>
struct DataType< ::wasp_logistics::GetPoseResponse>
{
  static const char* value()
  {
    return DataType< ::wasp_logistics::GetPose >::value();
  }
  static const char* value(const ::wasp_logistics::GetPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WASP_LOGISTICS_MESSAGE_GETPOSE_H
