// Generated by gencpp from file wasp_logistics/LogisticsActionGoal.msg
// DO NOT EDIT!


#ifndef WASP_LOGISTICS_MESSAGE_LOGISTICSACTIONGOAL_H
#define WASP_LOGISTICS_MESSAGE_LOGISTICSACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <wasp_logistics/LogisticsGoal.h>

namespace wasp_logistics
{
template <class ContainerAllocator>
struct LogisticsActionGoal_
{
  typedef LogisticsActionGoal_<ContainerAllocator> Type;

  LogisticsActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  LogisticsActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::wasp_logistics::LogisticsGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct LogisticsActionGoal_

typedef ::wasp_logistics::LogisticsActionGoal_<std::allocator<void> > LogisticsActionGoal;

typedef boost::shared_ptr< ::wasp_logistics::LogisticsActionGoal > LogisticsActionGoalPtr;
typedef boost::shared_ptr< ::wasp_logistics::LogisticsActionGoal const> LogisticsActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator1> & lhs, const ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator1> & lhs, const ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wasp_logistics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23dd76de537ba1274182942ef637dc62";
  }

  static const char* value(const ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23dd76de537ba127ULL;
  static const uint64_t static_value2 = 0x4182942ef637dc62ULL;
};

template<class ContainerAllocator>
struct DataType< ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wasp_logistics/LogisticsActionGoal";
  }

  static const char* value(const ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"LogisticsGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: wasp_logistics/LogisticsGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"bool active\n"
"float32 distance\n"
"int32 liftup\n"
"int32 liftdown\n"
"#float32 startpoint_x\n"
"#float32 startpoint_y\n"
"#float32 startpoint_z\n"
"#float32 startpoint_w\n"
"#float32 endpoint_x\n"
"#float32 endpoint_y\n"
"#float32 endpoint_z\n"
"#float32 endpoint_w\n"
;
  }

  static const char* value(const ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LogisticsActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wasp_logistics::LogisticsActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::wasp_logistics::LogisticsGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WASP_LOGISTICS_MESSAGE_LOGISTICSACTIONGOAL_H
