// Generated by gencpp from file wasp_logistics/TrolleyAlignGoal.msg
// DO NOT EDIT!


#ifndef WASP_LOGISTICS_MESSAGE_TROLLEYALIGNGOAL_H
#define WASP_LOGISTICS_MESSAGE_TROLLEYALIGNGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace wasp_logistics
{
template <class ContainerAllocator>
struct TrolleyAlignGoal_
{
  typedef TrolleyAlignGoal_<ContainerAllocator> Type;

  TrolleyAlignGoal_()
    : align(false)  {
    }
  TrolleyAlignGoal_(const ContainerAllocator& _alloc)
    : align(false)  {
  (void)_alloc;
    }



   typedef uint8_t _align_type;
  _align_type align;





  typedef boost::shared_ptr< ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator> const> ConstPtr;

}; // struct TrolleyAlignGoal_

typedef ::wasp_logistics::TrolleyAlignGoal_<std::allocator<void> > TrolleyAlignGoal;

typedef boost::shared_ptr< ::wasp_logistics::TrolleyAlignGoal > TrolleyAlignGoalPtr;
typedef boost::shared_ptr< ::wasp_logistics::TrolleyAlignGoal const> TrolleyAlignGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator1> & lhs, const ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator2> & rhs)
{
  return lhs.align == rhs.align;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator1> & lhs, const ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace wasp_logistics

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d78b99c0a1f9f75d262b241769b0800";
  }

  static const char* value(const ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d78b99c0a1f9f75ULL;
  static const uint64_t static_value2 = 0xd262b241769b0800ULL;
};

template<class ContainerAllocator>
struct DataType< ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wasp_logistics/TrolleyAlignGoal";
  }

  static const char* value(const ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"bool align\n"
;
  }

  static const char* value(const ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.align);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrolleyAlignGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::wasp_logistics::TrolleyAlignGoal_<ContainerAllocator>& v)
  {
    s << indent << "align: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.align);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WASP_LOGISTICS_MESSAGE_TROLLEYALIGNGOAL_H
