# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from wasp_logistics/LogisticsGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class LogisticsGoal(genpy.Message):
  _md5sum = "eb138febd2383e49af85d47988e04ff4"
  _type = "wasp_logistics/LogisticsGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#goal definition
bool active
float32 distance
int32 liftup
int32 liftdown
#float32 startpoint_x
#float32 startpoint_y
#float32 startpoint_z
#float32 startpoint_w
#float32 endpoint_x
#float32 endpoint_y
#float32 endpoint_z
#float32 endpoint_w
"""
  __slots__ = ['active','distance','liftup','liftdown']
  _slot_types = ['bool','float32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       active,distance,liftup,liftdown

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LogisticsGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.active is None:
        self.active = False
      if self.distance is None:
        self.distance = 0.
      if self.liftup is None:
        self.liftup = 0
      if self.liftdown is None:
        self.liftdown = 0
    else:
      self.active = False
      self.distance = 0.
      self.liftup = 0
      self.liftdown = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_Bf2i().pack(_x.active, _x.distance, _x.liftup, _x.liftdown))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.active, _x.distance, _x.liftup, _x.liftdown,) = _get_struct_Bf2i().unpack(str[start:end])
      self.active = bool(self.active)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_Bf2i().pack(_x.active, _x.distance, _x.liftup, _x.liftdown))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.active, _x.distance, _x.liftup, _x.liftdown,) = _get_struct_Bf2i().unpack(str[start:end])
      self.active = bool(self.active)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_Bf2i = None
def _get_struct_Bf2i():
    global _struct_Bf2i
    if _struct_Bf2i is None:
        _struct_Bf2i = struct.Struct("<Bf2i")
    return _struct_Bf2i
