// Generated by gencpp from file waypoint_navi/wpexecuteFeedback.msg
// DO NOT EDIT!


#ifndef WAYPOINT_NAVI_MESSAGE_WPEXECUTEFEEDBACK_H
#define WAYPOINT_NAVI_MESSAGE_WPEXECUTEFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace waypoint_navi
{
template <class ContainerAllocator>
struct wpexecuteFeedback_
{
  typedef wpexecuteFeedback_<ContainerAllocator> Type;

  wpexecuteFeedback_()
    : sequence()  {
    }
  wpexecuteFeedback_(const ContainerAllocator& _alloc)
    : sequence(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _sequence_type;
  _sequence_type sequence;





  typedef boost::shared_ptr< ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct wpexecuteFeedback_

typedef ::waypoint_navi::wpexecuteFeedback_<std::allocator<void> > wpexecuteFeedback;

typedef boost::shared_ptr< ::waypoint_navi::wpexecuteFeedback > wpexecuteFeedbackPtr;
typedef boost::shared_ptr< ::waypoint_navi::wpexecuteFeedback const> wpexecuteFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator1> & lhs, const ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.sequence == rhs.sequence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator1> & lhs, const ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace waypoint_navi

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b81e37d2a31925a0e8ae261a8699cb79";
  }

  static const char* value(const ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb81e37d2a31925a0ULL;
  static const uint64_t static_value2 = 0xe8ae261a8699cb79ULL;
};

template<class ContainerAllocator>
struct DataType< ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "waypoint_navi/wpexecuteFeedback";
  }

  static const char* value(const ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#feedback\n"
"int32[] sequence\n"
"\n"
;
  }

  static const char* value(const ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sequence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wpexecuteFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::waypoint_navi::wpexecuteFeedback_<ContainerAllocator>& v)
  {
    s << indent << "sequence[]" << std::endl;
    for (size_t i = 0; i < v.sequence.size(); ++i)
    {
      s << indent << "  sequence[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.sequence[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAYPOINT_NAVI_MESSAGE_WPEXECUTEFEEDBACK_H
