// Generated by gencpp from file waypoint_navi/wpexecuteGoal.msg
// DO NOT EDIT!


#ifndef WAYPOINT_NAVI_MESSAGE_WPEXECUTEGOAL_H
#define WAYPOINT_NAVI_MESSAGE_WPEXECUTEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace waypoint_navi
{
template <class ContainerAllocator>
struct wpexecuteGoal_
{
  typedef wpexecuteGoal_<ContainerAllocator> Type;

  wpexecuteGoal_()
    : execute(false)  {
    }
  wpexecuteGoal_(const ContainerAllocator& _alloc)
    : execute(false)  {
  (void)_alloc;
    }



   typedef uint8_t _execute_type;
  _execute_type execute;





  typedef boost::shared_ptr< ::waypoint_navi::wpexecuteGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::waypoint_navi::wpexecuteGoal_<ContainerAllocator> const> ConstPtr;

}; // struct wpexecuteGoal_

typedef ::waypoint_navi::wpexecuteGoal_<std::allocator<void> > wpexecuteGoal;

typedef boost::shared_ptr< ::waypoint_navi::wpexecuteGoal > wpexecuteGoalPtr;
typedef boost::shared_ptr< ::waypoint_navi::wpexecuteGoal const> wpexecuteGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::waypoint_navi::wpexecuteGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::waypoint_navi::wpexecuteGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::waypoint_navi::wpexecuteGoal_<ContainerAllocator1> & lhs, const ::waypoint_navi::wpexecuteGoal_<ContainerAllocator2> & rhs)
{
  return lhs.execute == rhs.execute;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::waypoint_navi::wpexecuteGoal_<ContainerAllocator1> & lhs, const ::waypoint_navi::wpexecuteGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace waypoint_navi

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::waypoint_navi::wpexecuteGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::waypoint_navi::wpexecuteGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waypoint_navi::wpexecuteGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::waypoint_navi::wpexecuteGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoint_navi::wpexecuteGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::waypoint_navi::wpexecuteGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::waypoint_navi::wpexecuteGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "371e747b927788fd0b8812d474ff9a56";
  }

  static const char* value(const ::waypoint_navi::wpexecuteGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x371e747b927788fdULL;
  static const uint64_t static_value2 = 0x0b8812d474ff9a56ULL;
};

template<class ContainerAllocator>
struct DataType< ::waypoint_navi::wpexecuteGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "waypoint_navi/wpexecuteGoal";
  }

  static const char* value(const ::waypoint_navi::wpexecuteGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::waypoint_navi::wpexecuteGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#goal definition\n"
"bool execute\n"
;
  }

  static const char* value(const ::waypoint_navi::wpexecuteGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::waypoint_navi::wpexecuteGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.execute);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wpexecuteGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::waypoint_navi::wpexecuteGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::waypoint_navi::wpexecuteGoal_<ContainerAllocator>& v)
  {
    s << indent << "execute: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.execute);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAYPOINT_NAVI_MESSAGE_WPEXECUTEGOAL_H
